### ISSUE TITLE
Scala Compilation is broken on master branch and recent PRs

### ISSUE THREAD

**Issue by pjfanning** [apache/linkis#5482]
This appears to be an issue going back a number of months.

Example:
https://github.com/apache/linkis/actions/runs/32231570826/job/96002330745

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.7.1:compile (scala-compile-first) on project linkis-module: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.7.1:compile failed: Compilation failed: InterfaceCompileFailed -> [Help 1]
```

The logs before that have warnings but I'm not sure what the issue is that makes the build bail out.

I got Claude AI to research it and it seems to indicate bb26ad363 is the issue. #5456

**Comment by pjfanning** [comment]
Some more analysis after opening #5483. The build breakage comes from the recent batch of `[SECURITY]` commits, and it is broader than just the Scala compile failure.

### Scala compile failure (fixed in #5483)

- bb26ad363 (#5456) — `ServerConfiguration.scala` references `LinkisModuleErrorCodeSummary.CRYPT_KEY_INSECURE`, but that enum constant was never added → `not found: value CRYPT_KEY_INSECURE`
- 047ebde76 (#5457) — `SecurityFilter.scala` uses `CommonVars` without importing it → `not found: value CommonVars`

Because `linkis-module` fails, every downstream module is skipped, so the whole build has been red.

### Code format check fails on master

`./mvnw spotless:check` (the `check-code-format` workflow) fails on master independently of the compile issue. Six files have pre-existing spotless violations:

- `linkis-common/.../TicketCipher.java` (#5460)
- `linkis-module/.../ServerConfiguration.scala` (#5456)
- `linkis-module/.../SSOUtils.scala`, `SecurityFilter.scala`, `SecurityFilterTest.scala` (#5457 / #5458)
- `linkis-eureka/.../EurekaSecurityConfig.java`

None of these were run through `spotless:apply` before merge. Because spotless checks the whole reactor, every PR now fails this job regardless of what it changes.

### sql-check fails on master

`linkis-dist/package/db/linkis_dml.sql` line 682 (`'instance'` row of the `INSERT INTO linkis_ps_dm_datasource_type_key` at line 670) has 17 values for 16 columns → `ERROR 1136 Column count doesn't match value count at row 11`. Introduced by f66a492f2 (#5450), which added a `value_regex` but left the `NULL` it replaced in place. One-token fix (drop one `NULL`).

### Unit tests fail once compilation is fixed

With #5483 applied, `ServerConfigurationTest` and `SecurityFilterTest.ignoreTimeoutSignalDefaultsTest` throw `ExceptionInInitializerError`: #5456 makes `ServerConfiguration` fail closed when `wds.linkis.crypt.key` is unset, and `linkis-module/src/test/resources/linkis.properties` does not set one. There are also unrelated failures in `linkis-common` (`ClassUtilsTest`, `TicketCipherTest.v1DecryptV2Ticket`).

### General issue

#5450, #5456, #5457, #5458 and #5460 between them broke compilation, formatting, the SQL init script and unit tests. Several are tagged `#AI COMMIT#`. Given that CI has been red for months, it looks like these were merged without a green (or any) CI run. It would be worth requiring the `check-code-format`, `sql-check` and build workflows to pass before merging — and running `./mvnw spotless:apply` locally before pushing — so that regressions like this get caught before they land.
